Added the generate-index service and timer to the setup script. Also, the generate_index script was not being inputted in the here document correctly as command substitution was being run, so I fixed the delimiter by adding "" around it.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -20,7 +20,7 @@ fi
 
 if [[ ! -f /var/lib/webgen/bin/generate_index ]]; then
     touch /var/lib/webgen/bin/generate_index
-    cat > /var/lib/webgen/bin/generate_index <<- isagi
+    cat > /var/lib/webgen/bin/generate_index <<- "isagi"
 #!/bin/bash
 
 set -euo pipefail
@@ -71,8 +71,59 @@ fi
 isagi
 if [[ $? -eq 0 ]]; then
     echo "Successfully created generate_index script at /var/lib/webgen/bin/generate_index."
+    chmod 755 /var/lib/webgen/bin/generate_index # make the script executable
 else
     echo "Error: Failed to create the file at /var/lib/webgen/bin/generate_index." >&2
+    exit 1
+fi
+fi
+
+
+#create the service and timer files
+if [[ ! -f /etc/systemd/system/generate-index.service ]]; then
+    touch /etc/systemd/system/generate-index.service
+    cat > /etc/systemd/system/generate-index.service <<- isagi
+[Unit]
+Description=Run generate_index script
+After=network-online.target
+Wants=network-online.target
+
+[Service]
+Type=oneshot
+ExecStart=/var/lib/webgen/bin/generate_index
+User=webgen
+Group=webgen
+
+[Install]
+WantedBy=multi-user.target
+isagi
+
+if [[ $? -eq 0 ]]; then
+    echo "Successfully created generate-index service at /etc/systemd/system/generate-index.service."
+else
+    echo "Error: Failed to create the file at /etc/systemd/system/generate-index.service." >&2
+    exit 1
+fi
+fi
+
+if [[ ! -f /etc/systemd/system/generate-index.timer ]]; then
+    touch /etc/systemd/system/generate-index.timer
+    cat > /etc/systemd/system/generate-index.timer <<- isagi
+[Unit]
+Description=Run generate-index service everyday at 5 AM
+
+[Timer]
+OnCalendar=*-*-* 05:00:00
+Persistent=true
+
+[Install]
+WantedBy=timers.target
+isagi
+
+if [[ $? -eq 0 ]]; then
+    echo "Successfully created generate-index timer at /etc/systemd/system/generate-index.timer."
+else
+    echo "Error: Failed to create the file at /etc/systemd/system/generate-index.timer." >&2
     exit 1
 fi
 fi
